name: build

on:
  push:
  pull_request:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-
    - uses: Swatinem/rust-cache@v2
      with:
        cache-targets: "false"
        cache-directories: |
          src-tauri/target
    - name: Install frontend dependencies
      run: yarn
    - uses: tauri-apps/tauri-action@v0
      id: tauri-build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}
        path: "${{ join(fromJSON(steps.tauri-build.outputs.artifactPaths), '\n') }}"
        if-no-files-found: error
