name: eslint

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    container: node:19
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: node_modules
        key: node-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node-modules-${{ runner.os }}-
    - name: Check eslint
      run: |
        yarn
        yarn lint --max-warnings 0
